"""Tests for the permutation group class."""

import pickle

import pytest

from drudge import Perm, Group


def test_s3_group_correct_and_serializable():
    """Test the S3 group.

    Since the permutation group objects are mostly opaque, here it is tested
    by its new arguments, which is also further verified to work with pickle.

    """

    cycle = Perm([1, 2, 0])
    transp = Perm([1, 0, 2], 1)
    group = Group([cycle, transp])

    args = group.__getnewargs__()
    assert len(args) == 1
    transvs = args[0]

    assert len(transvs) == 2
    top_level = transvs[0]
    lower_level = transvs[1]

    assert len(top_level) == 2
    target = top_level[0]
    transv = top_level[1]
    assert target == 0
    assert len(transv) == 2
    assert set(i[0][0] for i in transv) == {1, 2}

    assert len(lower_level) == 2
    target = lower_level[0]
    transv = lower_level[1]
    assert target == 1
    assert len(transv) == 1
    perm = transv[0]
    # This permutation fixes 0, but is not identity.  It must be the
    # transposition of 1 and 2
    assert perm[0][0] == 0
    assert perm[0][1] == 2
    assert perm[0][2] == 1
    assert perm[1] == 1

    # Args should not change from the group reconstructed from pickle.
    pickled = pickle.dumps(group)
    new_group = pickle.loads(pickled)
    assert new_group.__getnewargs__() == args

    # Assert that Group type should be considered true, since it implements
    # neither __bool__ nor __len__.
    assert group


def _closure(gens, size):
    """Close the generators into the full group by brute force.

    The elements are given as pairs of the pre-image tuple and the accompanied
    action, for comparison with the enumeration from the group object.
    """

    ident = (tuple(range(size)), 0)
    elems = {ident}
    frontier = [ident]
    gen_elems = [(tuple(i[j] for j in range(size)), i.acc) for i in gens]
    while len(frontier) > 0:
        new = []
        for pre_imgs, acc in frontier:
            for gen_pre_imgs, gen_acc in gen_elems:
                prod = (
                    tuple(pre_imgs[i] for i in gen_pre_imgs),
                    acc ^ gen_acc,
                )
                if prod not in elems:
                    elems.add(prod)
                    new.append(prod)
                continue
            continue
        frontier = new
        continue

    return elems


@pytest.mark.parametrize(
    "gens, size, order",
    [
        # S3 x S3 with all transpositions negated, the T3 amplitude symmetry.
        (
            [
                Perm([1, 0, 2, 3, 4, 5], 1),
                Perm([0, 2, 1, 3, 4, 5], 1),
                Perm([0, 1, 2, 4, 3, 5], 1),
                Perm([0, 1, 2, 3, 5, 4], 1),
            ],
            6,
            36,
        ),
        # Dihedral group of the two-body interaction, mixing symmetric pair
        # swap and negated transposition.
        ([Perm([2, 3, 0, 1]), Perm([1, 0, 2, 3], 1)], 4, 8),
        # A cyclic group, which is not generated by transpositions.
        ([Perm([1, 2, 0])], 3, 3),
        # A single transposition.
        ([Perm([1, 0], 1)], 2, 2),
    ],
)
def test_group_enumerates_elements(gens, size, order):
    """Test the enumeration of the elements of groups.

    The elements from the group object are compared against the brute-force
    closure of the generators, both for the permutations and for the
    accompanied actions.
    """

    group = Group(gens)
    assert len(group) == order

    elems = group.elements()
    assert len(elems) == order
    assert all(isinstance(i, Perm) for i in elems)
    assert all(len(i) == size for i in elems)

    elem_set = {(tuple(i[j] for j in range(size)), i.acc) for i in elems}
    assert len(elem_set) == order
    assert elem_set == _closure(gens, size)

    # The identity should always be included.
    assert (tuple(range(size)), 0) in elem_set

    # The pickle representation should not be affected.
    new_group = pickle.loads(pickle.dumps(group))
    assert len(new_group) == order
    assert new_group.__getnewargs__() == group.__getnewargs__()
